Added: Documentation for TreeDataGrid Usage, Including Examples
Nexus-Mods/NexusMods.App pull request #1133
Opened 2024-03-26 13:23 UTC by Sewer56

![Induction](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/754dd4e8-6be2-4e52-ae9e-e5e4bdd2eecf)

Including examples you can compile and inspect.

2024-03-26 14:59 UTC, erri120 requested changes
The code in the documentation is duplicated in the example. The code should only be in the example. To prevent the documentation from becoming stale and outdated, code should only be in the example.

The documentation should explain the concept and then refer to the example.

2024-03-27 09:12 UTC, Al12rs commented
Just a heads up, I'd like to have a look as well before we merge

2024-03-27 09:48 UTC, Al12rs commented
Had my quick readthrough, just the comment above from me.

2024-03-27 14:38 UTC, Sewer56 commented on docs/development-guidelines/UICodingGuidelines.md
> +To create a TreeDataGrid, we will take the following steps:
Actually a very good point, I'll get that sorted.

2024-03-28 12:46 UTC, erri120 approved these changes

2024-03-28 12:50 UTC, merged