Perf: Persist ingested files in DiskToFileTree in batch
Nexus-Mods/NexusMods.App pull request #1208
Opened 2024-04-12 03:13 UTC by Sewer56

This fixes a bottleneck on ingest when ingesting 60k files.

```
Before: 385.5658 s/op
After: 3.0254 s/op
```

\> 100x improvement.

Tested with `DiskToFileTree` benchmark in `loadoutsynchronizer-benchmarks` branch.

2024-04-15 09:05 UTC, Al12rs requested changes

2024-04-15 09:05 UTC, Al12rs commented on src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
> +        var file = new List<AModFile>();
Rename `file` list to `newFiles`

2024-04-15 09:37 UTC, Al12rs commented on src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
> +        var file = new List<AModFile>();
I don't know if it is worth optimizing this at this point. This code is going to change with the MnemonicDB integration and likely after the Ingest Diff view backend implementation as well, where we can try to compute the diff once and reuse that in more optimal manner.

2024-04-15 11:08 UTC, Sewer56 commented on src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
> +        var file = new List<AModFile>();
That was my thought on this.

The API surface here will change, so what I did is the bare minimum to unbottleneck the operation so it runs in a 'bearable' amount of time.

2024-04-15 12:00 UTC, Sewer56 commented on src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
> +        var file = new List<AModFile>();
Ah, forgot to say.

If I ever get around to optimizing this properly, I'd simply make `AGamePathNodeTree.GetAllDescendentFiles` not return an enumerable, so I'd know the exact max size of it; and that'd be okay.

For now, we are where we are.

2024-04-16 13:07 UTC, Al12rs approved these changes

2024-04-16 13:07 UTC, merged