Update markdown styling
Nexus-Mods/NexusMods.App pull request #1394
Opened 2024-05-21 13:42 UTC by erri120

Resolves #943.

![2024-05-21_15-39-35](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/92892ace-9820-4bd8-9c97-282a25eb8bde)

2024-05-21 13:43 UTC, erri120 commented
Still need to fix images with new designs.

2024-05-21 14:32 UTC, Al12rs commented
Is this ready for review? If so could you add a comment about the LineHeight problem? So we don't try to set it again in the future

2024-05-22 10:07 UTC, Al12rs requested changes

2024-05-22 10:07 UTC, Al12rs commented on src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererView.axaml
> +                <!-- <Setter Property="LineHeight" Value="21" /> -->
Add a comment explaining why LineHeight is problematic, so we avoid trying to set it again in the future.

2024-05-22 12:49 UTC, Al12rs approved these changes

2024-05-22 13:06 UTC, merged