Disabled Creation of Multiple Loadouts for α Release
Nexus-Mods/NexusMods.App pull request #1416
Opened 2024-05-22 16:49 UTC by Sewer56

fixes #1389

This disables the creation of more than 1 loadout for the α Release.

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/a7c9adad-5200-4950-8ebb-1b7c562c3203)

The pill has been modified so the `View` button stretches to the size of the remaining space.

Post first α release, we can make the setting visible in Release builds.
Code for that is also provided.

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/eda12368-c69b-4536-8dda-ae00918985bb)

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/e77431cb-380f-4107-ac80-a651f3dd0c9e)

The pill with `Add` button restored.

-------------

Outside of that, unsupported games have been hidden from Release builds by default and the features have very clearly been marked as `Experimental` since we don't yet have visible Settings categories.

I also renamed the `manage-game` CLI command, since it was inaccurate with what it did given the recent changes. Somehow that slipped past review.

2024-05-22 18:42 UTC, halgari commented
Oh gosh, I'm going to be pedantic on this again. Didn't @Pickysaurus mention we wanted "Unsupported" not "Experimental"? Or was I not listening?

2024-05-22 18:46 UTC, Sewer56 commented
> Oh gosh, I'm going to be pedantic on this again. Didn't @Pickysaurus mention we wanted "Unsupported" not "Experimental"? Or was I not listening?

The response was in reference as to what to name the setting to enable all games. Which is called `Enable Unsupported Games`.

Because we don't have setting categories, I pretended text to the dangerous ones.

I could make.it so it says `(Unsupported) Enable Unsupported Games` though, even if it looks a bit weird.

2024-05-23 12:02 UTC, erri120 requested changes

2024-05-23 12:02 UTC, erri120 commented on src/NexusMods.App.UI/Controls/GameWidget/IGameWidgetViewModel.cs
> +    public bool CanAddMoreThanOneLoadout => false;
```suggestion
    public bool CanAddMoreThanOneLoadout { get; }
```

2024-05-23 12:02 UTC, erri120 commented on src/NexusMods.App.UI/Controls/GameWidget/GameWidgetViewModel.cs
> +    public bool CanAddMoreThanOneLoadout => _experimentalSettings.EnableMultipleLoadouts;
```suggestion
    public bool CanAddMoreThanOneLoadout { get; }
```

2024-05-23 12:02 UTC, erri120 commented on src/NexusMods.App.UI/Controls/GameWidget/GameWidgetViewModel.cs
> +        _experimentalSettings = settingsManager.Get<ExperimentalSettings>();
```suggestion
        CanAddMoreThanOneLoadout = settingsManager.Get<ExperimentalSettings>().EnableMultipleLoadouts;
```

2024-05-23 12:02 UTC, erri120 commented on src/NexusMods.App.UI/Controls/GameWidget/GameWidgetViewModel.cs
> +    private readonly ExperimentalSettings _experimentalSettings;
```suggestion
```

2024-05-23 12:05 UTC, erri120 approved these changes

2024-05-23 12:51 UTC, merged