Docs
Nexus-Mods/NexusMods.App pull request #1418
Opened 2024-05-22 18:44 UTC by Patriot99

I added a couple of changes to the documentation to make it slightly clearer and more concise. You may notice that in my version the difference is punctuation and the use of a semicolon, but the documentation for the user should be smooth to read and written correctly grammatically. Consider these as suggestions and let me know what you think.

2024-05-22 20:18 UTC, halgari commented
Only feedback here is I'd rather not use unicode quotes. Aside from that looks good

2024-05-22 21:29 UTC, Patriot99 commented
> Only feedback here is I'd rather not use unicode quotes. Aside from that looks good

Done.

2024-05-23 07:36 UTC, Al12rs requested changes

2024-05-23 07:36 UTC, Al12rs commented on docs/development-guidelines/AddingAGame.md
> +To have a game automatically recognised by the Nexus Mods App, create a class that inherits from `AGame`.
```suggestion
To have a game be automatically recognised by the Nexus Mods App, create a class that inherits from `AGame`.
```

2024-05-23 07:36 UTC, Al12rs commented on docs/misc/DrawbacksOfNexusApproach.md
> +!!! tip "For a 100 GB game, an additional 60-100 GB of space will be used once 'managed' with the Nexus Mods App."
```suggestion
!!! tip "For a 10 GB game, an additional 6-10 GB of space will be used once 'managed' with the Nexus Mods App."
```
The games we are actually targeting are not that big. We will likely never backup 100 GB of game files.

2024-05-23 08:25 UTC, Al12rs approved these changes

2024-05-23 08:25 UTC, merged