Settings improvements
Nexus-Mods/NexusMods.App pull request #1618
Opened 2024-06-13 09:22 UTC by erri120

- Added sections, resolves #1370.
- Assigned settings to sections, resolves #1571.
- Re-worded and re-organized settings.
- Can now add links to settings, added one to link to the Privacy site.

2024-06-13 10:31 UTC, Al12rs approved these changes
There are some translations that could be made, but would likely create conflicts with the other PRs we have, we can also do these in future prs.

2024-06-13 10:31 UTC, Al12rs commented on src/NexusMods.App.UI/Settings/LoadoutGridSettings.cs
> +                .WithDescription("Shows the Override mod, which contains files generated or modified during gameplay that aren't part of any specific mod.")
Consider translations

2024-06-13 10:31 UTC, Al12rs commented on src/NexusMods.CrossPlatform/LoggingSettings.cs
> +                    .WithDescription("Enables the ConsoleTarget (stdout) for all loggers.")
Consider translations

2024-06-13 10:31 UTC, Al12rs commented on src/NexusMods.App.UI/Pages/Settings/SettingsView.axaml.cs
> +                    view => view.ViewModel!.Sections
These are not expected to change right? This should not get triggered on every setting value change for example, right?

2024-06-13 10:31 UTC, Al12rs commented on src/NexusMods.Settings/Services.cs
> +                Name = "General",
Consider translation

2024-06-13 10:31 UTC, Al12rs commented on src/NexusMods.StandardGameLocators/GameLocatorSettings.cs
> +                    .WithDescription("Allows you to manage games installed with Xbox Game Pass.")
Consider translations

2024-06-13 10:52 UTC, Al12rs commented
Here tests are failing

2024-06-13 11:22 UTC, Al12rs approved these changes

2024-06-13 13:26 UTC, halgari commented
Wow, this looks *really* good! (haven't looked at the code, but the screenshots look awesome.

2024-06-13 14:09 UTC, captainsandypants commented
This is my bad but when we changed the diagnostics section to "Privacy", I should have also updated the icon.
See [updated design](https://www.figma.com/design/rR0I4C46je8VwwqCdrpc5U/%F0%9F%93%B1%E2%9A%99%EF%B8%8F-Settings-page?node-id=155-5457&t=z8a3NQf373myzElF-1). Fair enough if it's too late to change that now though.

2024-06-13 14:20 UTC, captainsandypants commented
"Minimum severity" diagnostic setting needs updated text.

[Figma link](https://www.figma.com/design/rR0I4C46je8VwwqCdrpc5U/%F0%9F%93%B1%E2%9A%99%EF%B8%8F-Settings-page?node-id=155-5457)

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/8dc40d85-3985-4b88-8e68-4c40657f3828)

2024-06-17 10:33 UTC, Al12rs requested changes

2024-06-17 10:33 UTC, Al12rs commented on src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/DiagnosticSettings.cs
> +                .WithDescription("Set the minimum severity for diagnostics. You will not be notified for diagnostics with a severity lower than the selected level.")
```suggestion
                .WithDescription("Set the minimum severity for Health Check diagnostics. You will not be notified about diagnostics with a severity lower than the selected level.")
```
From review with lausandy

2024-06-17 12:49 UTC, Al12rs approved these changes
@captainsandypants reviewed in call with me and this should be good to merge

2024-06-17 12:49 UTC, merged