Multiple loadouts UI part1
Nexus-Mods/NexusMods.App pull request #1736
Opened 2024-07-09 10:30 UTC by Al12rs

This is a first PR of multiple to implement designs for #401 
This is a work in progress.

### Includes:
- Initial LoadoutCard UI 
- Initial LoadoutBadge UI and code behind wiring (will likely redo UI with FlexPanel)
- Started using `FlexPanel` and added a few workarounds to accomodate it.
- Created a PR to fix some of the issues: https://github.com/AvaloniaUI/Avalonia.Labs/pull/74
- Reworked Spinner control from scratch since it didn't support arbitrary size scaling
-

2024-07-09 10:57 UTC, erri120 commented on src/NexusMods.App.UI/Controls/ModInfo/Loading/LoadingView.axaml
Does this really have to exist?

2024-07-09 11:14 UTC, erri120 requested changes
Looks good, only thing missing is the hover state on the entire card.

2024-07-09 11:14 UTC, Al12rs commented on src/NexusMods.App.UI/Controls/ModInfo/Loading/LoadingView.axaml
Idk, I just changed this to explicit size instead of using a Class

2024-07-09 11:20 UTC, Al12rs commented on src/NexusMods.App.UI/Controls/LoadoutBadge/ILoadoutBadgeVM.cs
> +    bool IsLoadoutInProgress { get; }
There is some relationship between Applied and InProgress but it isn't clear cut. 
I think this is simple and clear enough for now, we can revisit when adding functionality.

2024-07-09 11:22 UTC, erri120 commented on src/NexusMods.App.UI/Controls/LoadoutBadge/ILoadoutBadgeVM.cs
> +    bool IsLoadoutInProgress { get; }
What is "in-progress" even supposed to mean?

2024-07-09 11:23 UTC, Al12rs commented on src/NexusMods.App.UI/Controls/LoadoutBadge/ILoadoutBadgeVM.cs
> +    bool IsLoadoutInProgress { get; }
Applying (Synchronizing)

2024-07-09 11:25 UTC, Al12rs commented
I'm fine with not merging this for a while to clean this up, I just pushed what I had to move on to the bugs in the meantime, but yeah I wasn't really finished with this

2024-07-10 10:50 UTC, erri120 approved these changes

2024-07-15 08:11 UTC, merged