Loadout Item Synchronizer
Nexus-Mods/NexusMods.App pull request #1806
Opened 2024-07-24 19:55 UTC by halgari

Updates the Loadout Synchronizer to support the new LoadoutItem format

What's rather nasty about this is that the Synchronizer is about 1000 lines of code, and I really don't want to juggle all that in one file, so instead I cloned the following files. The Mod related code is now in `*Old`, and the non-prefixed version is the LoadoutItem code:

* ILoadoutSynchronizer
* ALoadoutSynchronizer
* SyncTree
* SyncTreeNode
* SyncActionGroupings (made generic to handle both SyncTreeNode types)
* StardewVallyeSynchronizer
* Cyberpunk2077Synchronizer
* Tests for all the above. 

Tests all pass, so we should be good to go. I did *not* make the new synchronizers backwards compatible. That is to say if you create a loadout with `*Old` it should work with the new Synchronizer, but not vice versa. At any rate all of this shadow state is a stop-gap until we rework the rest of the codebase. 

Side comment: 

  * Converting between model types is a pain. I have to go LoadoutItem -> LoadoutItemWithTargedPath -> LoadoutFile -> CybeprunkFile. 
  * Querying for these is also a pain due to type conversations, the more I work on this the more I want a query language. Because all I want is this in some of the code (as a Datomic Datalog query):
  
  ```clojure
    :in db, ?manifestPath
    :find [?smapiMod, ?manifestFile]
    :where [
      [?manifestFile, LoadoutItemWithTargetdPath.TargetPath, ?manifestPath]
      [?manifestFile, LoadoutItem.Parent, ?smapiMod]
      [?smapiMod, SMAPILoadoutItem.Manifest, ?manifestFile]
    ]
  ```
  
  But instead I currently have this mess:
  
  ```csharp
      private static bool TryGetSMAPIMod(RelativePath modDirectoryName, Loadout.ReadOnly loadout, IDb db, out SMAPIModLoadoutItem.ReadOnly mod)
    {
        var manifestFilePath = new GamePath(LocationId.Game, Constants.ModsFolder.Join(modDirectoryName).Join(Constants.ManifestFile));

        if (!LoadoutItemWithTargetPath.FindByTargetPath(db, manifestFilePath)
                .TryGetFirst(x => x.AsLoadoutItem().LoadoutId == loadout && x.Contains(SMAPIManifestLoadoutFile.IsManifestMarker), out var file))
        {
            mod = default(SMAPIModLoadoutItem.ReadOnly);
            return false;
        }

        mod = SMAPIModLoadoutItem.Load(db, file.AsLoadoutItem().Parent);
        return true;
    }
  ```

2024-07-24 20:28 UTC, Sewer56 commented
(I could technically review this, but I'm not at all familiar with the new LoadoutItems system, so I'd need to study it. I'll leave for someone else to pick up)

2024-07-25 10:02 UTC, erri120 requested changes

2024-07-25 10:02 UTC, erri120 commented on src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
I don't know if you want to spend more time cleaning this up, we can come back to this later.

This is still full of references to old concepts (mostly in comments, function, variable, and parameter names), and has a couple of unused methods like `CreateGameFilesMod`, `SetFileStore`, and `IsLastLoadoutAVanillaStateLoadout`.

2024-07-25 12:19 UTC, halgari commented on src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
> +            }
Later in the file we use `loadoutFile` by checking `item.LoadoutFile` and that makes the compiler freak out. It's written this way to make the compiler happy.

2024-07-25 15:26 UTC, erri120 approved these changes

2024-07-25 15:33 UTC, merged