Added: Chevron to Diagnostic Items & Drop Shadow
Nexus-Mods/NexusMods.App pull request #1949
Opened 2024-08-27 20:24 UTC by Sewer56

fixes #1796

- https://github.com/Nexus-Mods/NexusMods.App/issues/1796

![image](https://github.com/user-attachments/assets/a3a6bd6a-8f92-40ff-84a6-43c69fbac9b3)

Getting that shadow to appear was quite the hassle (and wasted a lot of my time!!) due to how sizing works within the panel.

Notably it also it did not want to apply to the button [NavigationControl] itself; so I reserved some margin area for the shadow. It does mean the inner content is smaller, but the difference is not very big.

2024-08-28 08:19 UTC, Al12rs requested changes

2024-08-28 08:19 UTC, Al12rs commented on src/NexusMods.App.UI/Controls/Diagnostics/DiagnosticEntryView.axaml
> +            <chevron:Chevron Grid.Column="1"
This should just be a `UnifiedIcon`, it does not need to be a dedicated control. If you need pointerover put it in a border or button.

2024-08-28 08:19 UTC, Al12rs commented on src/NexusMods.App.UI/Controls/Chevron/Chevron.axaml
> +<UserControl xmlns="https://github.com/avaloniaui"
This doesn't need to exist

2024-08-29 07:59 UTC, Al12rs commented on src/NexusMods.App.UI/NexusMods.App.UI.csproj
> +      <UpToDateCheckInput Remove="Controls\Chevron\Chevron.axaml" />
Leftover from old files, can be removed

2024-08-29 09:19 UTC, insomnious commented
![image](https://github.com/user-attachments/assets/b9ecee70-02b8-4627-a026-539dc8669c31)

2024-08-29 09:28 UTC, Al12rs commented on src/NexusMods.App.UI/Controls/Diagnostics/DiagnosticEntryView.axaml
> +                </panels:FlexPanel>
You shouldn't be using Horizontal and vertical alignment on the child elements when using `FlexPanel` as it basically overrides the FlexPanel own layout.

To get the distribution you want you should try playing with `JustifyContent` property on the FlexPanel. It determines the distribution of items along the main axis (horizontal in this case).

I think SpaceBetween is likely what we want with Flex.Grow=1 on the TextBlock to allow it to take up as much space in the middle as available.

2024-08-29 09:30 UTC, Al12rs requested changes
Some adjustments for FlexPanel. I think in this case a Grid with `Auto,*,Auto` columns and manual padding between them could also work.

2024-08-29 10:40 UTC, insomnious commented
Removed the extra alignments and moved all styles to the Style file. Laurence noted that the MaxWidth wasn't set anywhere and so it doesn't [stay in middle of view](https://www.figma.com/design/hsUiqro210T3tsK1F9l1fQ/%F0%9F%93%B1%F0%9F%A9%BAHealth-Check?node-id=204-3029&t=AlUpeSqXdI3i5Vjb-1). He's happy with how it looks now but I'm not happy it's hard coded into the `DiagnosticListView.axaml` file along with some other styles that are already there. It'll serve it's purpose for now until we move to phase 2 of Health Check (as per [Figma](https://www.figma.com/design/hsUiqro210T3tsK1F9l1fQ/%F0%9F%93%B1%F0%9F%A9%BAHealth-Check?node-id=1-3041&t=AlUpeSqXdI3i5Vjb-1)), and I've left a `TODO` in the code.

2024-08-29 12:03 UTC, Al12rs commented
@insomnious Could you update this ticket with the stuff that was covered in this PR?
https://github.com/Nexus-Mods/NexusMods.App/issues/1091

2024-08-29 17:38 UTC, Al12rs approved these changes
Code looks good, did lausandy already look at the UI results?

2024-09-02 09:46 UTC, captainsandypants approved these changes
Looks great!

2024-09-02 09:54 UTC, merged