Improve: Small Cleanup / Tech Debt Reduction Around NexusWebApi / V2 Types.
Nexus-Mods/NexusMods.App pull request #2095
Opened 2024-09-26 06:18 UTC by Sewer56

This PR continues from:

- #2092

It should be merged after that PR.
Also contributes a bit towards:

- https://github.com/Nexus-Mods/NexusMods.App/issues/2091#issue-2549044273

----------

# Summary

This PR moves the types from 
- #2092

Into the mainline `NexusWebApi` abstractions project.
I refrained from doing that in #2092 because it would make PR reviewing very annoying.

In addition some work is done to help migration towards the V2 API.

## Changelog

- `ModUpdates` project now uses types in `NexusWebApi` abstractions.
- Types which are confirmed to exist in V2 (GraphQL) API are placed in a `V2` folder to prevent accidental future deletion when getting rid of REST APIs.
- The structs `ModId`, `FileId`, `GameId` now use the correct field size (`u32`)
   - They are *not* `u64` like in our previous definition. This has been verified with both backend and GraphQL documentation.
- Implemented `UidForFile` and `UidForMod`.
    - These allow us to split up UID composite keys returned from the website into their specific components, (`GameId`+ `ModId`) or (`GameId`+`FileId`).
    - Methods to decode strings in V2 API results into `Uid` variants are provided.

2024-09-26 14:39 UTC, halgari requested changes
Didn't mean to approve it above

2024-09-26 14:40 UTC, Sewer56 commented on tests/Networking/NexusMods.Networking.ModUpdates.Tests/Tests.cs
> +    public void Test1() { }
Will fix in previous PR in chain.

2024-09-26 14:40 UTC, Sewer56 commented on src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/V2/Uid/UidForFile.cs
> +[StructLayout(LayoutKind.Sequential, Pack = 1)]
Consider it done.
I'll make a number of sample tests based on API responses.

2024-09-27 01:03 UTC, Sewer56 commented on src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/V2/Uid/UidForFile.cs
> +[StructLayout(LayoutKind.Sequential, Pack = 1)]
Done in e8e09e3213447437f232977646393573ca0cdf77

2024-09-27 01:04 UTC, Sewer56 commented on tests/Networking/NexusMods.Networking.ModUpdates.Tests/Tests.cs
> +    public void Test1() { }
Done in e4349be69b8ef1fee3a2de7612df9ed01b4f8dd6

2024-10-03 15:53 UTC, merged