Free Pill UI Banner
Nexus-Mods/NexusMods.App pull request #2118
Opened 2024-10-02 18:48 UTC by MistaOmega

Closes #1535 

Premium still working:
![image](https://github.com/user-attachments/assets/9c70c25f-e276-49f6-addb-b81307fc2039)

Free:
![image](https://github.com/user-attachments/assets/687046ca-4ed5-4bfb-93eb-9a01b9b9c133)

2024-10-03 02:09 UTC, Sewer56 approved these changes

2024-10-07 08:49 UTC, Pickysaurus commented
We'll need to check with @captainsandypants but I think the "FREE" text not being there is intended.

2024-10-07 08:54 UTC, MistaOmega commented
Also looked back at the issue and realised I didn't make it link to the page requested, so I should do that if this ends up still be required

2024-10-07 09:26 UTC, captainsandypants commented
I don't mind this being a thing for now but plan to explore having a "Get premium" type button up there

2024-10-07 09:28 UTC, Pickysaurus commented
> Also looked back at the issue and realised I didn't make it link to the page requested, so I should do that if this ends up still be required

@MistaOmega if possible can you add the link as the original ticket mentions? I think we can merge it for now. Although as captainsandypants said it will be changed at some point in the future!

2024-10-08 08:53 UTC, erri120 requested changes

2024-10-08 08:53 UTC, erri120 commented on src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
> +            var uri = new Uri("https://users.nexusmods.com/account/billing/premium?pk_campaign=NexusModsApp");
Use the `NexusModsUrlBuilder`:

```csharp
NexusModsUrlBuilder.CreateGenericUri("https://users.nexusmods.com/account/billing/premium");
```

2024-10-08 12:08 UTC, MistaOmega commented
@erri120 for note i've changed the other 2 uses of new Uri, to use the builder also

2024-10-08 12:37 UTC, erri120 approved these changes

2024-10-09 13:27 UTC, merged