Remove Download Page
Nexus-Mods/NexusMods.App pull request #2331
Opened 2024-12-02 15:59 UTC by insomnious

Closes https://github.com/Nexus-Mods/NexusMods.App/issues/2312

Just commented out Services lines for now as we'll bring it back at some point

2024-12-03 10:43 UTC, erri120 requested changes
You can just delete the files, the history is still in git.

2024-12-05 08:33 UTC, Al12rs commented on src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
> +        //Downloads.Click = ReactiveCommand.Create(NavigateToDownloads);
Can be removed as well

2024-12-05 09:50 UTC, insomnious commented on src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
> +        //Downloads.Click = ReactiveCommand.Create(NavigateToDownloads);
Oops

2024-12-05 11:23 UTC, Al12rs approved these changes

2024-12-05 12:08 UTC, erri120 approved these changes

2024-12-09 09:10 UTC, merged