Miscellaneous FOMOD Improvements (fixes #198)
Nexus-Mods/NexusMods.App pull request #237
Opened 2023-03-31 20:55 UTC by Sewer56

# Changes

- XML installer tests now run on actual stubbed `.fomod` files.
  - And there's tests for `.7z` and `.rar` files.  
- Added additional test cases for FOMODs.  
- FOMODs that specify an Asset/Image URL should no longer break CLI.  
- Added: Functionality to add names to tables.
  - Tables for groups now have titles.
- FOMOD tests now double as integration tests; some code was unstubbed, and we now also test communication between `IFileAnalyzer` and `IModInstaller`.
- FOMODs are now entirely loaded from memory, with no extraction from disk.  
- FOMODs with broken schema should no longer throw an exception; only log an error.  
- Images are now cached as part of analysis data [with the XML]. However, improvements can still be made, as the JSON gets serialized as Base64, increasing space use for images by 25%.  
- Cleaned up some of the code around FOMODs.  

## Remaining tasks

- Plugin/File Dependency Handling is not Yet Implemented.
  - Need to implement `IPluginDelegates` and look up the current loadout for files to be deployed.
  - Figure out all the files once and just look up in a dictionary.
  - It's unclear if it's possible to do this efficiently.
- Saving and Restoring User Preferences Across Re-Deployment.

2023-03-31 21:08 UTC, Sewer56 commented
This seems to be failing because after update of DataModel to main, `.sqlite` database handle isn't released after disposing the object pool in `SqliteDataStore`; I'm not sure why.

I'm doubling the unit test for installer as integration test, and thus use a real temporary datastore to ensure stuff transfers correctly from the analyzer to installer.

2023-03-31 21:17 UTC, halgari approved these changes
Lotta code here, but it's clean, and does what we need it to do

2023-03-31 21:24 UTC, Sewer56 commented
I think I know why;
https://github.com/Nexus-Mods/NexusMods.App/blob/15609d01e3f85f331770ba57b855ab8bc9805163/src/NexusMods.DataModel/ConnectionPoolPolicy.cs#L28

We open connections here but they never get closed down the road.

2023-03-31 21:53 UTC, Sewer56 commented
Okay, I figured out a fix; so I guess I fixed a bug on main too 😅

2023-03-31 23:26 UTC, erri120 commented
I'm gonna look at this over the weekend and on Monday.

2023-04-03 07:43 UTC, erri120 requested changes
The tests should ideally use `InMemoryFileSystem` as the `IFileSystem` implementation. Since you have "real" files that you want to test, adding a method `AddExistingFile` to `InMemoryFileSystem` and calling that as part of the test setup phase, should be enough to get this to work.

As part of #239, I will look into updating `TemporaryFileManager`.

2023-04-03 07:43 UTC, erri120 commented on src/NexusMods.Paths/TemporaryFileManager.cs
> +    // TODO: For unit tests we should inject IFileSystem here.
Will look into that (#239).

2023-04-03 09:01 UTC, Sewer56 commented
@erri120 I am aware the tests currently run on the FileSystem. I did originally try to write the code to be entirely in memory; though I felt that the improvements needed to make that possible warrant separate issues/tickets. ~~I was also running out of time in the Sprint~~

More specifically, we need:  
- An In-Memory `IDataStore` .  
- Unpacking of `.7z` and `.rar` in memory (In-Memory `FileExtractor`).
  - We currently use binary `7z`/`7zz` for unpacking; thus can't use in-memory FileSystem.
  - or we just drop non-zip tests entirely; that's probably ok too.
- `TemporaryFileManager` needs `IFileSystem` support as noted in TODO; this is now tracked in https://github.com/Nexus-Mods/NexusMods.App/issues/239.

I felt like some of these were more appropriate to be done at the same time we transition the entire codebase to using `IFileSystem`; allowing for other existing tests to also be done in-memory.

2023-04-03 11:50 UTC, erri120 approved these changes

2023-04-04 06:11 UTC, merged