WIP Healthcheck redesign
Nexus-Mods/NexusMods.App pull request #2397
Opened 2024-12-17 13:27 UTC by insomnious

Closes https://github.com/Nexus-Mods/NexusMods.App/issues/2382

Gets Health Check up to date with Figma including new brand pictogram, subtab control and mutliline health check entries.

Doesn't include tweaking the left hand menu styles as that's a future task.

2024-12-17 13:37 UTC, insomnious commented on src/NexusMods.App.UI/WorkspaceSystem/Page/APageViewModel.cs
> +
oops, that was to get a design view working

2024-12-17 13:38 UTC, erri120 commented on src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml
> +                    <TabItem Header="All (12)" x:Name="AllDiagnosticsTab">
Either remove the header or set it to an empty string.

2024-12-17 13:38 UTC, erri120 commented on src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml
> +                    <TabItem Header="Critical (6)" x:Name="CriticalDiagnosticsTab">
Either remove the header or set it to an empty string.

2024-12-17 13:39 UTC, erri120 commented on src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml
> +                </TabControl>
Remove the headers or replace them with an empty string. You can also move the body contents into a resource se we can re-use them.

2024-12-17 13:41 UTC, erri120 requested changes
See comments.

2024-12-17 13:42 UTC, erri120 commented on src/NexusMods.App.UI/WorkspaceSystem/Page/APageViewModel.cs
> +
You can check other design views as examples, you'd wanna do this:

```csharp
public MyDesignViewModel() : base(windowManager: nulll!) { }
```

2024-12-17 13:44 UTC, insomnious commented on src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml.cs
> +                    .DisposeWith(disposable);
Any thoughts on how else to filter?

2025-01-02 08:14 UTC, Pickysaurus commented
@insomnious Not sure if it's in scope with what you're doing here, but this would be handy and a (hopefully) small tweak. https://github.com/Nexus-Mods/NexusMods.App/issues/2418

2025-01-06 10:51 UTC, Al12rs commented
Closed and reopened to rebase CI merge builds onto latest main

2025-01-06 11:28 UTC, erri120 requested changes

2025-01-06 11:28 UTC, erri120 commented on src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListViewModel.cs
> +        // });
```suggestion
```

2025-01-06 11:28 UTC, erri120 commented on src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListViewModel.cs
> +    //public ReactiveCommand<DiagnosticSeverity, Unit> ToggleSeverityCommand { get; }
```suggestion
```

2025-01-06 11:28 UTC, erri120 commented on src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListViewModel.cs
> +    //public ReactiveCommand<Unit, Unit> ShowAllCommand { get; }
```suggestion
```

2025-01-06 11:28 UTC, erri120 commented on src/NexusMods.App.UI/Pages/Diagnostics/List/IDiagnosticListViewModel.cs
> +    //ReactiveCommand<DiagnosticSeverity, Unit> ToggleSeverityCommand { get; }
```suggestion
```

2025-01-06 11:28 UTC, erri120 commented on src/NexusMods.App.UI/Pages/Diagnostics/List/IDiagnosticListViewModel.cs
> +    //ReactiveCommand<Unit, Unit> ShowAllCommand { get; }
```suggestion
```

2025-01-06 15:38 UTC, erri120 approved these changes

2025-01-06 15:49 UTC, merged