Upgrade deps
Nexus-Mods/NexusMods.App pull request #347
Opened 2023-06-07 14:35 UTC by halgari

2023-06-09 13:23 UTC, halgari commented on src/NexusMods.App.UI/Controls/Spine/Buttons/Icon/IconButton.axaml
> +            <!--<Setter Property="BorderDashArray" Value="2, 2" />-->
These are not supported in Avalonia 11, will re-enable them later

2023-06-09 13:24 UTC, halgari commented on src/NexusMods.App.UI/Initializers.cs
> +    public static IImage IImage => new WriteableBitmap(new PixelSize(16, 16), new Vector(96, 96), PixelFormat.Rgba8888, AlphaFormat.Opaque);
This can't run until Avalonia's DI is setup, so moving it to a computed property fixes that race condition

2023-06-09 13:25 UTC, halgari commented on src/NexusMods.App.UI/RightContent/LoadoutGrid/LoadoutGridView.axaml
> +    <Grid RowDefinitions="Auto, *">
Must be in a grid to allow the DataGrid to work with item virtualization

2023-06-12 08:04 UTC, erri120 requested changes

2023-06-12 08:26 UTC, erri120 approved these changes

2023-06-12 11:36 UTC, merged