Switch to xxhash64 nuget
Nexus-Mods/NexusMods.App pull request #559
Opened 2023-08-16 00:16 UTC by halgari

resolves #550

2023-08-16 07:51 UTC, erri120 requested changes

2023-08-16 07:51 UTC, erri120 commented on Directory.Packages.props
Sadly, using the in-built package manager of Rider and VS will completely scramble this file. I'd suggest keeping the same formatting as before or merging all groups into one and sort it lexically.

2023-08-16 18:26 UTC, halgari commented on Directory.Packages.props
I'm confused at what you mean by this, looking at the history it doesn't look like this file has changed much much in this PR. What am I missing?

2023-08-17 16:37 UTC, halgari commented on Directory.Packages.props
done

2023-08-21 14:53 UTC, merged