WIP: FOMOD UI
Nexus-Mods/NexusMods.App pull request #600
Opened 2023-09-04 11:28 UTC by erri120

Part of #316.

2023-09-11 10:43 UTC, Al12rs requested changes

2023-09-11 11:16 UTC, erri120 commented on src/Games/NexusMods.Games.FOMOD.UI/Options/IGuidedInstallerOptionViewModel.cs
> +    public bool IsEnabled { get; set; }
`IsEnabled` is also a property that input elements have and indicate whether the control is enabled for user interaction:

```csharp
this.OneWayBind(ViewModel, vm => vm.IsEnabled, view => view.RadioButton.IsEnabled)
    .DisposeWith(disposables);
```

2023-09-11 11:16 UTC, erri120 commented on src/Games/NexusMods.Games.FOMOD.UI/GuidedInstallerUi.cs
> +        activeStepViewModel.TaskCompletionSource = tcs;
It makes no difference.

2023-09-11 11:37 UTC, Al12rs commented on src/Games/NexusMods.Games.FOMOD.UI/Options/IGuidedInstallerOptionViewModel.cs
> +    public bool IsEnabled { get; set; }
Yeah, and that is a shame. I would still use IsInteractable to avoid confusion in the rest of the code, but you decide.

2023-09-18 11:45 UTC, halgari approved these changes

2023-09-18 11:51 UTC, Al12rs approved these changes

2023-09-18 12:37 UTC, merged