Move back to nx archivemanager
Nexus-Mods/NexusMods.App pull request #659
Opened 2023-09-21 04:05 UTC by halgari

Currenty this still fails due to a ZStd decompression error in the SDV tests. The unit tests for the archive manager work fine. But something with how SDV is doing things is causing this to fail.

2023-09-21 04:07 UTC, halgari commented
@Sewer56 mind taking a look at `NxArchiveManager.ChunkedArchiveStream.*`? I'm sure I'm missing something. If you run the SDV tests you'll see "no installer found for X". But if you then run with debugging enabled you'll see a ZStd error being thrown by the NX `Compression.Decompress` method. I'm sure I'm doing something wrong here, but I can't figure out what it is.

2023-09-21 10:10 UTC, Sewer56 commented
Sure, I got some time to spare. 

The advanced installer suggestion stuff I'm finishing up is dependent on AL's current work (their work changes API I have to interface with); so it'd be more efficient for me to fully wait until that's finalised anyway, as I've been working off of an incomplete PR.

2023-09-25 08:24 UTC, Al12rs commented
Is this ready for review?

2023-09-27 20:00 UTC, Sewer56 requested changes
Address the changes above then it's good for merging.
I'll detail the performance gimmick I mentioned earlier in a new issue. We can adjust the text of that issue as needed.

2023-09-28 00:51 UTC, Sewer56 commented on src/NexusMods.DataModel/NxArchiveManager.cs
> +                _blocks.Add(block);
This can be preallocated as array rather than using list; since the number of blocks (chunkCount) is known ahead of time.

2023-09-28 15:51 UTC, merged